### ISSUE TITLE
LVDT tolerance functionality

### ISSUE THREAD

**Issue by dsand** [so-90prime/bok-90prime-gui#2]
As with the 'old' fw-gui we would like to have some LVDT tolerance functionality.  This will ensure that commanded LVDT request are reached (at least to within the tolerance specified).  I know Phil has added some of this functionality into his ngserver.

For bonus points, if the user tries for an LVDT tolerance below 5, we should give them a warning that this is not a realistic request.

**Comment by davner** [comment]
Here is how I would approach this. 

**GUI**
- Add tolerance input for LVDTs(default 10) 
  - This would be auto built from a INumberProperty from the driver
- Add warning if tolerance is below 5 (popup or red warning string below input)

**INDI Driver (bokGalil)**
- Create a INumberVectorProperty called tolerance or add it to the current INumberVectorProperty for LVDT move entering
- Move actuators in a loop until values are within the tolerance with max number of tries

I don't believe we should use the GUI to send multiple actuator moves, it should be the driver that handles that. 

I'm interested to hear @pndaly's thoughts. Looking at what he built for Mike L. to use over NGServer, this should be a quick modification since he has it implemented already.

**Comment by dsand** [comment]
My understanding is the @pndaly has made progress on this issue at the last run.  LVDT tolerance has been built into Ngserver and now needs to be propagated to the GUI.

**Comment by dsand** [comment]
Closing this, seem to work very well now.
